### ISSUE TITLE
Add database indexes

### ISSUE THREAD

**Issue by jondubois** [Leasehold/ldpos-knex-dal#2]
Refer to the database schema https://gist.github.com/jondubois/22581a5ab6b6bd64d8385fbc2a17d5db - Indexes are listed under each table definition.

The indexes should be created automatically when the node is launched for the first time (part of the DAL `init` method).

**Comment by sacOO7** [comment]
I have added indexes for mentioned fields. You can check schema for the same under
https://github.com/Leasehold/ldpos-knex-dal/tree/master/knex/migrations

**Comment by sacOO7** [comment]
Marking issue as resolved, since we have added indexes to mentioned fields in the schema.
