### ISSUE TITLE
Fix format for monetary values to support correct sorting in database

### ISSUE THREAD

**Issue by jondubois** [Leasehold/ldpos-knex-dal#3]
Refer to the database schema https://gist.github.com/jondubois/22581a5ab6b6bd64d8385fbc2a17d5db - Monetary values should be stored in the database in such a way that they can be sorted and indexed efficiently (BigInt?).

For compatibility reasons with clients and signature verification logic, the application logic passes those values to the DAL as strings but they should be stored in a numeric format because they need to be fetched ordered numerically (not lexicographically),

The monetary values are (for each table):

```
accounts:
- balance

transactions:
- amount
- fee

delegates:
- voteWeight
```

**Comment by sacOO7** [comment]
I have marked mentioned fields as BigIntegers. You can check schema for the same under
https://github.com/Leasehold/ldpos-knex-dal/tree/master/knex/migrations

**Comment by sacOO7** [comment]
Marking issue as resolved, since above fields are marked as bigIntegers.
